name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below to help us understand and evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a [user type], I want [goal] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions you've considered
      placeholder: "Alternative approaches..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: How would this feature be used?
      placeholder: |
        1. User scenario one...
        2. User scenario two...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocking workflow)
        - High (significant improvement)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      options:
        - label: This may require breaking changes
        - label: This affects API design
        - label: This impacts performance
        - label: This requires documentation updates
        - label: I'm willing to help implement this

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots