name: Performance Issue
description: Report performance problems or optimization needs
title: "[Performance]: "
labels: ["performance", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Performance issues require specific metrics and context. Please provide as much detail as possible.

  - type: input
    id: operation
    attributes:
      label: Operation/Task
      description: What operation is slow?
      placeholder: "e.g., Model training, Inference, Data loading"
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Performance Metrics
      description: Current vs expected performance
      placeholder: |
        Current: 10 seconds per batch
        Expected: 2-3 seconds per batch
        Memory usage: 8GB peak
        GPU utilization: 45%
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Specifications
      description: Detailed hardware information
      placeholder: |
        GPU: RTX 4090 (24GB VRAM)
        CPU: Intel i9-12900K (16 cores)
        RAM: 32GB DDR4
        Storage: NVMe SSD
    validations:
      required: true

  - type: textarea
    id: dataset
    attributes:
      label: Dataset/Model Information
      description: Relevant dataset and model details
      placeholder: |
        Model size: 7B parameters
        Dataset size: 1M samples
        Batch size: 16
        Sequence length: 2048
    validations:
      required: true

  - type: textarea
    id: profiling
    attributes:
      label: Profiling Data
      description: Any profiling or benchmark results
      render: shell